# Generated by Django 5.2 on 2025-05-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mark_as_watched', models.BooleanField(default=False)),
                ('lesson_number', models.IntegerField(unique=True)),
                ('embed_code', models.TextField(default='', help_text='Paste the Bunny.net embed iframe code here.')),
                ('bunny_video_id', models.CharField(blank=True, help_text="The video ID from Bunny.net (e.g., 'eefdc431-726a-4ccc-b2f1-127b9aa449a5')", max_length=255, null=True)),
                ('bunny_library_id', models.CharField(default='420524', editable=False, max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.videosection')),
            ],
        ),
    ]
