# Generated by Django 5.2 on 2025-05-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='embed_code',
        ),
    ]
