# Generated by Django 5.2 on 2025-05-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='embed_code',
            field=models.TextField(default='x', help_text='Paste the Bunny.net embed iframe code here.'),
        ),
    ]
