# Generated by Django 5.2 on 2025-05-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='lesson_number',
            field=models.IntegerField(default=0),
        ),
    ]
