# Generated by Django 5.2 on 2025-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_coursevideo_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='lesson_number',
            field=models.IntegerField(unique=True),
        ),
    ]
