# Generated by Django 5.2 on 2025-05-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_coursevideo_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='embed_code',
            field=models.TextField(default='', help_text='Paste the Bunny.net embed iframe code here.'),
        ),
    ]
