<<<<<<< HEAD
# Generated by Django 5.0 on 2025-05-04 02:09
=======
# Generated by Django 5.2 on 2025-05-04 02:23
>>>>>>> dba5c33c64178db2769a8b075f8439a2ef7f23dd

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('content', '0003_alter_coursevideo_lesson_number'),
=======
        ('content', '0003_alter_coursevideo_embed_code'),
>>>>>>> dba5c33c64178db2769a8b075f8439a2ef7f23dd
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='bunny_library_id',
            field=models.CharField(blank=True, default='420524', help_text="The library ID from Bunny.net (e.g., '420524')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text="The video ID from Bunny.net (e.g., 'eefdc431-726a-4ccc-b2f1-127b9aa449a5')", max_length=255, null=True),
        ),
<<<<<<< HEAD
        migrations.AlterField(
            model_name='coursevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
=======
>>>>>>> dba5c33c64178db2769a8b075f8439a2ef7f23dd
    ]
