# Generated by Django 5.2 on 2025-05-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_coursevideo_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='bunny_library_id',
            field=models.CharField(blank=True, default='420524', help_text="The library ID from Bunny.net (e.g., '420524')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text="The video ID from Bunny.net (e.g., 'eefdc431-726a-4ccc-b2f1-127b9aa449a5')", max_length=255, null=True),
        ),
    ]
