# Generated by Django 5.0 on 2025-05-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_coursevideo_bunny_library_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='video',
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='bunny_library_id',
            field=models.CharField(default='420524', editable=False, max_length=255),
        ),
    ]
