# Generated by Django 5.2 on 2025-05-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_coursevideo_bunny_library_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='bunny_library_id',
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='video',
        ),
    ]
