"""
Django settings for behind_the_search project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tp6n30jo9e_sfal453(4#fsr5vl82bzv4tz@8!0tbm!c531tyx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'content',
    'users.apps.UsersConfig',
    'phonenumber_field',
    'adminBoard.apps.AdminboardConfig',
    'notifications',
]

AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.PageDurationMiddleware',  # Add the new middleware
]

ROOT_URLCONF = 'behind_the_search.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'behind_the_search.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'behindthesearch1@gmail.com'
EMAIL_HOST_PASSWORD = 'pnzn porg ucoh qcoj'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LOGIN_REDIRECT_URL = 'sections_list'
LOGOUT_REDIRECT_URL = 'landing-page'

# Discord Webhook Settings
DISCORD_WEBHOOKS = {
    # For new user registrations
    'registration': 'https://discord.com/api/webhooks/1368746010687311955/ykmTl2PV6yjtyRYdCJDQEqtLfo9P0OkSbY0HCcIExZo3IJ9d7QjcdKyt0pcNbIpfmUrf',
    # For user logins
    'login': 'https://discord.com/api/webhooks/1368746035190694142/AluQTULY6iDaJ8eDVc4uS6lXwXnC0wWCpNnBTXhUOP3ocagQXZIAv9HeEVd0DVw9DFy-',
    # For video watching activity
    'video_watch': 'https://discord.com/api/webhooks/1368746039607034008/g7cDn8ummXM7DAxrcF8pIe0EHI42PerzxPTtwYJE8Co647KkR_AwWdySg2ZEUt4-ogV1',
    # For page visit tracking
    'page_visit': 'https://discord.com/api/webhooks/1368746042400706690/-faf-uybXOciwLf0fj0m7G8v_52x_p3oApOHvOh3ssn4-lJPrzUalURz9C-0pCfGsPut',
    # For security events
    'security': 'https://discord.com/api/webhooks/1368746044782805134/Z9PWTObj9-cgcQlrQvjG7WLOoIhEuN7V4i9cUUGnBxgbfPf3YyLg3oaFYJaLax1MqjWt',
}

# IP Geolocation API Key
# Sign up at ipapi.com or similar service
# IP_GEOLOCATION_API_KEY = 'YOUR_API_KEY_HERE'
