# Generated by Django 5.2 on 2025-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
