# Generated by Django 5.0 on 2025-05-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='lesson_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='coursevideo',
            unique_together={('section', 'lesson_number')},
        ),
    ]
