# Generated by Django 5.0 on 2025-05-04 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_coursevideo_lesson_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
