# Generated by Django 5.2 on 2025-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_uservideoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='bunny_library_id',
            field=models.CharField(default='421350', editable=False, max_length=255),
        ),
    ]
